--
-- Copyright © 2013-2018, The SeedStack authors <http://seedstack.org>
--
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.
--

CREATE TABLE SEED_I18N_KEY (
   ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    OUTDATED BIT,
    PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE SEED_I18N_KEY_TRANS (
    KEY_ID VARCHAR(255) NOT NULL,
    TRANSLATIONS_KEY_ID VARCHAR(255) NOT NULL,
    TRANSLATIONS_LOCALE VARCHAR(255) NOT NULL,
    PRIMARY KEY (KEY_ID, TRANSLATIONS_KEY_ID, TRANSLATIONS_LOCALE)
);
CREATE TABLE SEED_I18N_LOCALE (
    CODE VARCHAR(255) NOT NULL,
    DEFAULT_LOCALE BIT,
    ENGLISH_LANGUAGE VARCHAR(255),
    LANGUAGE VARCHAR(255),
    PRIMARY KEY (CODE)
);
CREATE TABLE SEED_I18N_TRANSLATION (
    KEY_ID VARCHAR(255) NOT NULL,
    LOCALE VARCHAR(255) NOT NULL,
    APPROXIMATE BIT,
    OUTDATED BIT,
    TRANSLATION VARCHAR(255),
    PRIMARY KEY (KEY_ID, LOCALE)
);
ALTER TABLE SEED_I18N_KEY_TRANS
   ADD UNIQUE (TRANSLATIONS_KEY_ID, TRANSLATIONS_LOCALE);

ALTER TABLE SEED_I18N_KEY_TRANS
   ADD FOREIGN KEY (TRANSLATIONS_KEY_ID, TRANSLATIONS_LOCALE)
   REFERENCES SEED_I18N_TRANSLATION (KEY_ID, LOCALE);

ALTER TABLE SEED_I18N_KEY_TRANS
   ADD FOREIGN KEY (KEY_ID)
   REFERENCES SEED_I18N_KEY (ID);
